package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Kid;
import org.mybatis.cdi.Mapper;

@Mapper
public interface KidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int insert(Kid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    Kid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    List<Kid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int updateByPrimaryKey(Kid record);
}