package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.KidsGroup;
import org.mybatis.cdi.Mapper;

@Mapper
public interface KidsGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KIDS_GROUP
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KIDS_GROUP
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int insert(KidsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KIDS_GROUP
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    KidsGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KIDS_GROUP
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    List<KidsGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KIDS_GROUP
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    int updateByPrimaryKey(KidsGroup record);
}