package lt.vu.mybatis.model;

import java.util.Date;

public class Kid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KID.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KID.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KID.FIRSTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KID.LASTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KID.GROUPID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private Integer groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KID.ID
     *
     * @return the value of PUBLIC.KID.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KID.ID
     *
     * @param id the value for PUBLIC.KID.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KID.BIRTHDATE
     *
     * @return the value of PUBLIC.KID.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KID.BIRTHDATE
     *
     * @param birthdate the value for PUBLIC.KID.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KID.FIRSTNAME
     *
     * @return the value of PUBLIC.KID.FIRSTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KID.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.KID.FIRSTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KID.LASTNAME
     *
     * @return the value of PUBLIC.KID.LASTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KID.LASTNAME
     *
     * @param lastname the value for PUBLIC.KID.LASTNAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KID.GROUPID
     *
     * @return the value of PUBLIC.KID.GROUPID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KID.GROUPID
     *
     * @param groupid the value for PUBLIC.KID.GROUPID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    public KidsGroup getGroup(){ return group; }
    public void setGroup(KidsGroup group){ this.group = group; }
    private KidsGroup group;
}