package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Leader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEADER.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEADER.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEADER.EMAIL
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEADER.NAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEADER.PHONENO
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    private String phoneno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEADER.ID
     *
     * @return the value of PUBLIC.LEADER.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEADER.ID
     *
     * @param id the value for PUBLIC.LEADER.ID
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEADER.BIRTHDATE
     *
     * @return the value of PUBLIC.LEADER.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEADER.BIRTHDATE
     *
     * @param birthdate the value for PUBLIC.LEADER.BIRTHDATE
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEADER.EMAIL
     *
     * @return the value of PUBLIC.LEADER.EMAIL
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEADER.EMAIL
     *
     * @param email the value for PUBLIC.LEADER.EMAIL
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEADER.NAME
     *
     * @return the value of PUBLIC.LEADER.NAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEADER.NAME
     *
     * @param name the value for PUBLIC.LEADER.NAME
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEADER.PHONENO
     *
     * @return the value of PUBLIC.LEADER.PHONENO
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEADER.PHONENO
     *
     * @param phoneno the value for PUBLIC.LEADER.PHONENO
     *
     * @mbg.generated Mon May 04 00:06:01 EEST 2020
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    public List<KidsGroup> getGroupList(){ return groupsList; }
    public void setGroupList(List<KidsGroup> groupsList){ this.groupsList = groupsList; }
    private List<KidsGroup> groupsList = new ArrayList<>();
}